[project]
name = "naqsha-e-safar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "networkx>=3.5",
    "osmnx>=2.0.6",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]
